### ISSUE TITLE
show label inside the pie graph

### ISSUE THREAD

**Issue by kamit971** [giacomocerquone/react-native-fab-pie#2]
Hi team,
thank you so much for this lovely framework, can you please help me to add a label or alertview any thing inside the pie for each individual. i am waiting for your reply. Thanks

**Comment by giacomocerquone** [comment]
If I understood correctly, you want to press on a piece of the pie and then alert the user, so you wanna do something onPress.
There is a problem on the main library that doesn't allow you to do this, so I don't know how to help, sorry.
